### ISSUE TITLE
Properties with Null Value

### ISSUE THREAD

**Issue by atpyatt** [grofit/knockout.merge#13]
I have found that properties with a null value are being treated in the fromJS function in the same way as properties that have a value which is an object that needs to be recursed through. This is because koModel[parameter]=null satisfies the condition below:

else if (typeof (koModel[parameter]) == "object" &&
                !(koModel[parameter] instanceof Date) &&
                !isArray(koModel[parameter])) {
          exports.fromJS(.....
}

Changing the condition to the following solved the problem for me: 

 else if (koModel[parameter] !== null && typeof (koModel[parameter]) == "object" &&
                !(koModel[parameter] instanceof Date) &&
                !isArray(koModel[parameter])) {
          exports.fromJS(.....
}

**Comment by grofit** [comment]
Just push up a change request with the test scenario if you can and I will get it put in.

**Comment by grofit** [comment]
All merged.
