### ISSUE TITLE
Complex Merge doesn't seem to work correctly

### ISSUE THREAD

**Issue by IPWright83** [grofit/knockout.merge#6]
I'm trying to write a 'complex' merge but it seems to be failing. Essentially my sub-properties are being overwritten with non-observable fields, when they should remain observable. I'm not sure why this is the case. You can see a JSFfiddle to demonstrate this (I found the issue when computed observables that I've taken out for simplicity couldn't read from sibling computed fields) http://jsfiddle.net/IPWright83/fnc0xysk/2/

So I've started by defining some data which I create a view model from using `ko.mapping.fromJS`:

````
var data = {
    name: "Sign-off",
    id: "XX",
    values: [{ text: "Signed-off", count: 150, color: "#5fb5cc" }, 
             { text: "Submitted", count: 90, color: "#75d181" }, 
             { text: "Not Submitted", count: 75, color: "#f8a25b" }
            ],
    aggregates: {
        count: 650
    }
};
var vm = ko.mapping.fromJS(data);
```` 

If I log the `vm`, then `vm.values[0]` and finally `vm.values[0].text` I get the following. Ending up with an observable field as I expected:

![image](https://cloud.githubusercontent.com/assets/1374775/8181336/eec873f4-141c-11e5-9f9c-3b808c56b26e.png)

Once I've done this I wait for a second and attempt to update the data using `ko.merge.fromJS` and this is where I start getting the problem:

````
ko.merge.fromJS(vm, {
    values: [{ text: "Signed-off", count: 90, color: "#5fb5cc" }, 
             { text: "Submitted", count: 40, color: "#75d181" }, 
             { text: "Not Submitted", count: 35, color: "#f8a25b" }
            ],
    aggregates: {
        count: 250
    }
});
````
Before I started I tested it on one of the top level fields, which seemed to work fine. But if I churn out the same information to the console you can now see that the text field on the first value is no longer observable :(

![image](https://cloud.githubusercontent.com/assets/1374775/8181374/2ba43dc6-141d-11e5-86ea-6bbc1604b0cf.png)

**Comment by grofit** [comment]
Checked out your example, off top of my head not a clue why its happening, there was a recent change which allowed for non observables to be copied over if the object was classed as empty on the receiving side.

That should only kick in if nothing else does but you could try removing the `isEmptyObject` check in the `fromJS` method and see if that fixes it, if so then maybe I need to be more clever in how I identify if an object should be merged when not being observable.

**Comment by IPWright83** [comment]
A quick step through the code `isEmptyObject` is not the culprit. It comes down to the merge methods. When looking at `values` there is no `mergeMethod` or `mergeRule` - though I'm not sure where these come from.

This means that it falls into the final branch of the code:

    else
        { knockoutElement(dataElement); }

The problem with this is it doesn't distinguish between an `observable` and an `observableArray`. Therefore it's assigning the value as a regular POJO rather than assigning each value with the array as an observable. So I think while recursion of observable objects is supported, recursion of observable array items isn't at the moment.

**Comment by grofit** [comment]
the `mergeMethod` and `mergeRule` are basically extensions to an observable to indicate some AoP style rules/methods to carry on on a merge... i.e if you had a date object you would want to take the string and convert it into a date object as part of the merge.

Adding support for observable arrays should not be too hard, I am swamped with stuff at the moment thought so I am not sure when I will get a chance to do anything, I have marked it as a bug as I can see it being a common use case, so if no one else fixes it within a reasonable time I will take a look.

**Comment by IPWright83** [comment]
I've submitted a pull request #7 that addresses this and certainly fixes the case that I demonstrated.
